import type { ArchitectureSubsystemEvidence } from "./types";
import { AIOS_PLATFORM_REPOSITORY } from "./repository-manifest";

const AIOS_ARCHITECTURE_EVIDENCE: readonly ArchitectureSubsystemEvidence[] = Object.freeze([
  {
    id: "harmony",
    name: "Harmony",
    purpose: "Coordinate AIOS work, routing, approvals, and Founder-facing operations.",
    owner: "Harmony",
    responsibilities: ["orchestration", "task routing", "Founder alignment"],
    layer: "orchestration",
    dependsOn: [
      { subsystemId: "ai-workforce", type: "agent", evidencePaths: ["src/lib/workforce/registry.ts"] },
      { subsystemId: "approval-engine", type: "service", evidencePaths: ["src/lib/harmony/os/approval-actions.ts"] },
      { subsystemId: "julius", type: "service", evidencePaths: ["src/lib/harmony/reflection.ts"] },
    ],
    routes: ["/harmony"],
    relatedTests: ["tests/unit/harmony-ui-certification.test.ts", "tests/unit/workforce-optimization.test.ts"],
    protectedComponents: ["Founder orchestration boundary"],
    publicInterfaces: ["Harmony authenticated application routes"],
    internalInterfaces: ["workforce routing", "reflection", "operational planning"],
    runtimeServices: ["Harmony orchestration runtime"],
    evidencePaths: ["src/lib/harmony/operator-intake.ts", "src/lib/harmony/agents/a2a.ts", "src/lib/workforce/registry.ts"],
    criticalitySignals: ["runtime_orchestration", "authorization_boundary"],
  },
  {
    id: "mason",
    name: "Mason",
    purpose: "Plan and coordinate governed engineering work for AIOS itself.",
    owner: "Mason",
    responsibilities: ["repository reasoning", "engineering planning", "governed execution coordination"],
    layer: "intelligence",
    dependsOn: [
      { subsystemId: "julius", type: "service", evidencePaths: ["src/lib/workforce/mason-action.ts"] },
      { subsystemId: "approval-engine", type: "service", evidencePaths: ["src/lib/harmony/autonomy/mason-policy.ts"] },
      { subsystemId: "execution-ledger", type: "database", evidencePaths: ["src/lib/harmony/code/mason-ledger.ts"] },
      { subsystemId: "connector-runtime", type: "import", evidencePaths: ["src/lib/harmony/code/mason-production-runtime.ts"] },
    ],
    databaseObjects: ["mason_execution_ledger", "mason_execution_events"],
    relatedTests: ["tests/unit/mason.test.ts", "tests/unit/mason-closed-loop.test.ts", "tests/unit/mason-policy.test.ts"],
    relatedWorkflows: ["Launch Validation"],
    protectedComponents: ["Founder-only Mason boundary", "merge approval boundary"],
    internalInterfaces: ["Mason production runtime", "closed-loop coordinator", "execution policy bridge"],
    externalDependencies: ["GitHub", "Vercel"],
    runtimeServices: ["Mason deterministic runtime", "shared AI provider runtime"],
    agentKeys: ["mason"],
    knownUnknowns: ["External Foundry Mason deployment is configured outside this repository."],
    evidencePaths: ["src/lib/harmony/code/mason.ts", "src/lib/workforce/mason-action.ts", "src/lib/workforce/mason-closed-loop.ts"],
    criticalitySignals: ["production_execution", "authorization_boundary", "persistent_data"],
  },
  {
    id: "julius",
    name: "Julius",
    purpose: "Provide company-scoped organizational memory and retrieval infrastructure.",
    owner: "Atlas",
    responsibilities: ["knowledge retrieval", "memory persistence", "context isolation"],
    layer: "intelligence",
    dependsOn: [
      { subsystemId: "supabase", type: "database", evidencePaths: ["src/lib/julius/service.ts"] },
      { subsystemId: "authentication", type: "service", evidencePaths: ["src/lib/julius/permissions.ts"] },
    ],
    databaseObjects: ["julius_entries", "julius_relations"],
    routes: ["/harmony/julius"],
    relatedTests: ["tests/unit/julius-permissions.test.ts", "tests/unit/julius-mason-retrieval.test.ts"],
    protectedComponents: ["company memory isolation"],
    publicInterfaces: ["company-scoped Julius retrieval"],
    internalInterfaces: ["retrieval", "knowledge graph", "writeback"],
    runtimeServices: ["Julius retrieval runtime"],
    knownUnknowns: ["Live retrieval health is certified separately from source architecture."],
    evidencePaths: ["src/lib/julius/service.ts", "src/lib/julius/retrieval.ts", "src/lib/julius/permissions.ts"],
    criticalitySignals: ["persistent_data", "authorization_boundary"],
  },
  {
    id: "ai-workforce",
    name: "AI Workforce",
    purpose: "Define canonical AIOS agents, responsibilities, and agent relationships.",
    owner: "Harmony",
    responsibilities: ["agent registry", "agent identity", "workforce relationships"],
    layer: "orchestration",
    dependsOn: [
      { subsystemId: "julius", type: "agent", evidencePaths: ["src/lib/workforce/registry.ts"] },
      { subsystemId: "connector-runtime", type: "service", evidencePaths: ["src/lib/workforce/registry.ts"] },
    ],
    relatedTests: ["tests/unit/workforce-registry.test.ts", "tests/unit/workforce-certification.test.ts"],
    publicInterfaces: ["AIOS_WORKFORCE registry"],
    internalInterfaces: ["agent connector mapping", "Founder-only agent classification"],
    agentKeys: ["harmony", "auditor", "mason", "catalyst", "ambassador", "atlas", "pulse", "horizon", "aegis", "ledger"],
    evidencePaths: ["src/lib/workforce/registry.ts"],
    criticalitySignals: ["runtime_orchestration"],
  },
  {
    id: "atlas",
    name: "Atlas",
    purpose: "Steward Julius and maintain organizational knowledge continuity.",
    owner: "Harmony",
    responsibilities: ["knowledge stewardship", "documentation", "decision history"],
    layer: "intelligence",
    dependsOn: [
      { subsystemId: "ai-workforce", type: "agent", evidencePaths: ["src/lib/workforce/registry.ts"] },
      { subsystemId: "julius", type: "service", evidencePaths: ["src/lib/workforce/registry.ts"] },
    ],
    relatedTests: ["tests/unit/workforce-registry.test.ts"],
    internalInterfaces: ["Julius steward relationship"],
    agentKeys: ["atlas"],
    evidencePaths: ["src/lib/workforce/registry.ts"],
    criticalitySignals: ["supporting_service"],
  },
  {
    id: "catalyst",
    name: "Catalyst",
    purpose: "Support AIOS content and growth workflows through governed providers.",
    owner: "Harmony",
    responsibilities: ["content generation", "campaign planning", "growth experimentation"],
    layer: "experience",
    dependsOn: [
      { subsystemId: "ai-workforce", type: "agent", evidencePaths: ["src/lib/workforce/registry.ts"] },
      { subsystemId: "connector-runtime", type: "service", evidencePaths: ["src/lib/workforce/registry.ts"] },
    ],
    relatedTests: ["tests/unit/workforce-registry.test.ts"],
    internalInterfaces: ["agent connector mapping"],
    agentKeys: ["catalyst"],
    evidencePaths: ["src/lib/workforce/registry.ts", "src/lib/harmony/content/generation.ts"],
    criticalitySignals: ["supporting_service"],
  },
  {
    id: "ledger",
    name: "Ledger",
    purpose: "Maintain AIOS approval, activity, and compliance records.",
    owner: "Harmony",
    responsibilities: ["approval records", "audit trails", "compliance tracking"],
    layer: "governance",
    dependsOn: [
      { subsystemId: "ai-workforce", type: "agent", evidencePaths: ["src/lib/workforce/registry.ts"] },
      { subsystemId: "approval-engine", type: "service", evidencePaths: ["src/lib/workforce/registry.ts"] },
      { subsystemId: "execution-ledger", type: "service", evidencePaths: ["src/lib/workforce/registry.ts"] },
    ],
    relatedTests: ["tests/unit/workforce-registry.test.ts", "tests/unit/mason-ledger.test.ts"],
    internalInterfaces: ["approval and execution record stewardship"],
    agentKeys: ["ledger"],
    evidencePaths: ["src/lib/workforce/registry.ts", "src/lib/ledger/index.ts"],
    criticalitySignals: ["persistent_data", "supporting_service"],
  },
  {
    id: "founder-os",
    name: "Founder OS",
    purpose: "Provide company ownership, objectives, work, and Founder-governed operating surfaces.",
    owner: "Founder",
    responsibilities: ["company operations", "Founder directives", "work governance"],
    layer: "experience",
    dependsOn: [
      { subsystemId: "authentication", type: "service", evidencePaths: ["src/lib/harmony/os/company-actions.ts"] },
      { subsystemId: "approval-engine", type: "service", evidencePaths: ["src/lib/harmony/os/approval-actions.ts"] },
      { subsystemId: "supabase", type: "database", evidencePaths: ["src/lib/harmony/os/work-actions.ts"] },
    ],
    databaseObjects: ["companies", "founder_directives", "work_items"],
    routes: ["/harmony/operations", "/harmony/work", "/harmony/approvals"],
    relatedTests: ["tests/unit/os-foundation.test.ts", "tests/unit/approval-center-unified.test.ts"],
    protectedComponents: ["Founder company boundary"],
    publicInterfaces: ["Founder OS authenticated routes"],
    internalInterfaces: ["company actions", "work actions", "approval actions"],
    evidencePaths: ["src/lib/harmony/os/company-actions.ts", "src/lib/harmony/os/work-actions.ts", "supabase/migrations/20260601000600_founder_os_foundation.sql"],
    criticalitySignals: ["authorization_boundary", "persistent_data"],
  },
  {
    id: "approval-engine",
    name: "Approval Engine",
    purpose: "Enforce Founder decisions before governed execution.",
    owner: "Founder",
    responsibilities: ["approval persistence", "decision validation", "execution resumption"],
    layer: "governance",
    dependsOn: [
      { subsystemId: "authentication", type: "service", evidencePaths: ["src/lib/harmony/os/approval-actions.ts"] },
      { subsystemId: "supabase", type: "database", evidencePaths: ["src/lib/data/os/approvals.ts"] },
      { subsystemId: "execution-ledger", type: "runtime", evidencePaths: ["src/lib/harmony/autonomy/execution-resumption.ts"] },
    ],
    databaseObjects: ["approvals", "approval_payloads"],
    routes: ["/harmony/approvals"],
    apis: ["POST /api/harmony/autonomy/approve"],
    relatedTests: ["tests/unit/approval-resume-route.test.ts", "tests/unit/approval-consistency.test.ts"],
    protectedComponents: ["Founder approval decision", "exact approval payload"],
    publicInterfaces: ["approval review route", "approval resume API"],
    internalInterfaces: ["approval store", "execution resumption"],
    runtimeServices: ["Approval runtime"],
    evidencePaths: ["src/lib/harmony/os/approval-actions.ts", "src/lib/data/os/approvals.ts", "src/app/api/harmony/autonomy/approve/route.ts"],
    criticalitySignals: ["authorization_boundary", "production_execution", "persistent_data"],
  },
  {
    id: "execution-ledger",
    name: "Execution Ledger",
    purpose: "Record append-only Mason execution and event evidence.",
    owner: "Ledger",
    responsibilities: ["execution evidence", "event history", "idempotency support"],
    layer: "governance",
    dependsOn: [
      { subsystemId: "supabase", type: "database", evidencePaths: ["src/lib/harmony/code/mason-ledger.ts"] },
      { subsystemId: "authentication", type: "service", evidencePaths: ["supabase/migrations/20260717000000_mason_execution_ledger.sql"] },
    ],
    databaseObjects: ["mason_execution_ledger", "mason_execution_events"],
    relatedTests: ["tests/unit/mason-ledger.test.ts", "tests/unit/mason-closed-loop-snapshot-ledger.test.ts"],
    protectedComponents: ["append-only execution history", "RLS ownership"],
    internalInterfaces: ["Mason ledger adapter"],
    evidencePaths: ["src/lib/harmony/code/mason-ledger.ts", "supabase/migrations/20260717000000_mason_execution_ledger.sql"],
    criticalitySignals: ["persistent_data", "production_execution"],
  },
  {
    id: "event-mesh",
    name: "Event Mesh",
    purpose: "Transport typed AIOS runtime events through configured adapters and workers.",
    owner: "Harmony",
    responsibilities: ["event envelopes", "adapter routing", "worker dispatch"],
    layer: "runtime",
    dependsOn: [
      { subsystemId: "supabase", type: "database", evidencePaths: ["src/lib/event-mesh/adapters/postgres.ts"] },
      { subsystemId: "ai-workforce", type: "agent", evidencePaths: ["src/lib/event-mesh/workforce-handlers.ts"] },
      { subsystemId: "execution-ledger", type: "runtime", evidencePaths: ["src/lib/event-mesh/operations.ts"] },
    ],
    databaseObjects: ["event_mesh_events", "event_mesh_workers"],
    relatedTests: ["tests/unit/event-mesh-envelope.test.ts", "tests/unit/event-mesh-postgres-adapter.test.ts", "tests/unit/event-mesh-workforce-handlers.test.ts"],
    protectedComponents: ["event dispatch boundary"],
    internalInterfaces: ["local adapter", "Postgres adapter", "NATS adapter", "worker handlers"],
    externalDependencies: ["NATS when configured"],
    runtimeServices: ["Event Mesh worker"],
    knownUnknowns: ["Worker deployment availability is environment-specific."],
    evidencePaths: ["src/lib/event-mesh/index.ts", "src/lib/event-mesh/worker.ts", "supabase/migrations/20260713000000_event_mesh.sql"],
    criticalitySignals: ["runtime_orchestration", "persistent_data"],
  },
  {
    id: "connector-runtime",
    name: "Connector Runtime",
    purpose: "Resolve configured external connectors and enforce connector execution policy.",
    owner: "Harmony",
    responsibilities: ["connector registry", "health resolution", "policy-gated execution"],
    layer: "integration",
    dependsOn: [
      { subsystemId: "authentication", type: "service", evidencePaths: ["src/lib/integrations/connector-runtime.ts"] },
      { subsystemId: "supabase", type: "database", evidencePaths: ["src/lib/integrations/connector-runtime.ts"] },
      { subsystemId: "approval-engine", type: "service", evidencePaths: ["src/lib/harmony/autonomy/connector-policy.ts"] },
    ],
    databaseObjects: ["integration_connections"],
    apis: ["/api/integrations/[provider]/*"],
    relatedTests: ["tests/unit/connector-health.test.ts", "tests/unit/connector-policy.test.ts"],
    protectedComponents: ["encrypted connector tokens", "provider execution policy"],
    publicInterfaces: ["connector health APIs", "OAuth connection routes"],
    internalInterfaces: ["connector registry", "connector runtime adapter"],
    externalDependencies: ["configured provider APIs"],
    runtimeServices: ["Connector runtime"],
    evidencePaths: ["src/lib/integrations/connectors.ts", "src/lib/integrations/connector-runtime.ts", "src/lib/harmony/autonomy/connector-policy.ts"],
    criticalitySignals: ["authorization_boundary", "runtime_orchestration"],
  },
  {
    id: "marketplace",
    name: "Marketplace",
    purpose: "Publish, discover, version, and install AIOS marketplace items.",
    owner: "AIOS Product",
    responsibilities: ["catalog persistence", "versioning", "company installation"],
    layer: "experience",
    dependsOn: [
      { subsystemId: "authentication", type: "service", evidencePaths: ["src/lib/marketplace/actions.ts"] },
      { subsystemId: "supabase", type: "database", evidencePaths: ["src/lib/marketplace/persistence.ts"] },
    ],
    databaseObjects: ["marketplace_items", "marketplace_item_versions", "marketplace_item_ratings", "company_installations"],
    routes: ["/marketplace", "/harmony/marketplace"],
    relatedTests: ["tests/unit/marketplace-migration-foundation.test.ts"],
    publicInterfaces: ["marketplace catalog routes"],
    internalInterfaces: ["persistence", "discovery", "installation", "publishing"],
    evidencePaths: ["src/lib/marketplace/persistence.ts", "src/lib/marketplace/install.ts", "supabase/migrations/20260705090000_marketplace_persistence_foundation.sql"],
    criticalitySignals: ["persistent_data", "workflow_dependency"],
  },
  {
    id: "authentication",
    name: "Authentication",
    purpose: "Resolve Supabase sessions, profiles, and canonical AIOS roles.",
    owner: "AIOS Platform",
    responsibilities: ["session resolution", "role authorization", "middleware refresh"],
    layer: "platform",
    dependsOn: [{ subsystemId: "supabase", type: "service", evidencePaths: ["src/lib/supabase/server.ts"] }],
    databaseObjects: ["profiles"],
    routes: ["/login", "/auth/callback"],
    relatedTests: ["tests/unit/authenticated-experience.test.ts"],
    protectedComponents: ["session cookies", "Founder/admin role resolution"],
    publicInterfaces: ["login and auth callback"],
    internalInterfaces: ["server client", "middleware session refresh", "role helpers"],
    externalDependencies: ["Supabase Auth"],
    runtimeServices: ["Authentication runtime"],
    evidencePaths: ["src/lib/auth/actions.ts", "src/lib/auth/roles.ts", "src/lib/supabase/middleware.ts"],
    criticalitySignals: ["authentication_boundary", "authorization_boundary"],
  },
  {
    id: "billing",
    name: "Billing",
    purpose: "Enforce subscriptions and coordinate Stripe billing operations.",
    owner: "AIOS Platform",
    responsibilities: ["subscription enforcement", "checkout", "billing portal", "webhooks"],
    layer: "platform",
    dependsOn: [
      { subsystemId: "authentication", type: "service", evidencePaths: ["src/lib/billing/enforce.ts"] },
      { subsystemId: "supabase", type: "database", evidencePaths: ["src/lib/billing/store.ts"] },
    ],
    databaseObjects: ["billing_subscriptions"],
    apis: ["POST /api/billing/checkout", "POST /api/billing/portal", "POST /api/stripe/webhook"],
    protectedComponents: ["subscription enforcement", "Stripe webhook"],
    publicInterfaces: ["billing checkout and portal APIs"],
    internalInterfaces: ["billing store", "plan enforcement"],
    externalDependencies: ["Stripe"],
    evidencePaths: ["src/lib/billing/enforce.ts", "src/lib/billing/stripe.ts", "src/app/api/stripe/webhook/route.ts"],
    criticalitySignals: ["financial_transaction", "authorization_boundary", "persistent_data"],
  },
  {
    id: "supabase",
    name: "Supabase",
    purpose: "Provide AIOS persistence, RLS, authentication backing, and database functions.",
    owner: "AIOS Platform",
    responsibilities: ["Postgres persistence", "RLS enforcement", "storage and Auth integration"],
    layer: "data",
    dependsOn: [],
    databaseObjects: ["profiles", "companies", "approvals", "integration_connections"],
    relatedWorkflows: ["Full Migration Chain Certification", "Supabase Staging Migration Plan"],
    protectedComponents: ["RLS", "database credentials", "tenant isolation"],
    internalInterfaces: ["server client", "browser client", "admin-only client"],
    externalDependencies: ["Supabase managed platform"],
    runtimeServices: ["Supabase runtime"],
    knownUnknowns: ["Environment-specific live health requires authenticated runtime evidence."],
    evidencePaths: ["src/lib/supabase/server.ts", "src/lib/supabase/client.ts", "supabase/migrations/20260601000000_profiles_and_roles.sql"],
    criticalitySignals: ["authentication_boundary", "persistent_data", "production_execution"],
  },
]);

export function getDefaultMasonArchitectureEvidence(
  repository: string | null | undefined,
): readonly ArchitectureSubsystemEvidence[] {
  return repository?.trim().toLowerCase() === AIOS_PLATFORM_REPOSITORY.toLowerCase()
    ? AIOS_ARCHITECTURE_EVIDENCE
    : [];
}
