import type { EngineeringKnowledgeCatalog } from "./knowledge-types";
import { AIOS_PLATFORM_REPOSITORY } from "./repository-manifest";

const AIOS_ENGINEERING_KNOWLEDGE = Object.freeze({
  catalogId: "mason.engineering-knowledge",
  version: "1.0.0",
  asOf: "2026-07-23T00:00:00.000Z",
  memories: Object.freeze([
    {
      id: "memory.founder-governed-engineering",
      version: "1.0.0",
      category: "founder_engineering_decision",
      title: "Founder approval remains authoritative for governed engineering",
      summary: "Mason may plan and prepare governed work, but merge, production, and destructive operations remain Founder-controlled.",
      repositoryEvidence: ["src/lib/harmony/code/mason.ts", "src/lib/harmony/autonomy/mason-policy.ts"],
      relatedFiles: ["src/lib/harmony/code/mason.ts", "src/lib/harmony/autonomy/mason-policy.ts"],
      relatedSubsystems: ["mason", "approval-engine"],
      relatedTests: ["tests/unit/mason-policy.test.ts", "tests/unit/mason.test.ts"],
      relatedPrs: [454, 455],
      relatedIssues: [],
      origin: "founder_decision",
      verificationStatus: "verified",
      confidence: 1,
      owner: "Founder",
      createdAt: "2026-07-23T00:00:00.000Z",
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      status: "active",
    },
    {
      id: "memory.repository-unknowns-remain-unknown",
      version: "1.0.0",
      category: "repository_pattern",
      title: "Unknown repository facts remain UNKNOWN",
      summary: "Bounded repository and architecture analysis must not convert absent evidence into implementation facts.",
      repositoryEvidence: ["src/lib/harmony/code/mason-engineering/repository-intelligence.ts", "src/lib/harmony/code/mason-engineering/architectural-intelligence.ts"],
      relatedFiles: ["src/lib/harmony/code/mason-engineering/repository-intelligence.ts", "src/lib/harmony/code/mason-engineering/architectural-intelligence.ts"],
      relatedSubsystems: ["mason"],
      relatedTests: ["tests/unit/mason-engineering-foundation.test.ts", "tests/unit/mason-architectural-intelligence.test.ts"],
      relatedPrs: [454, 455],
      relatedIssues: [],
      origin: "repository",
      verificationStatus: "verified",
      confidence: 1,
      owner: "Mason",
      createdAt: "2026-07-23T00:00:00.000Z",
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      status: "active",
    },
    {
      id: "memory.validation-standard-suite",
      version: "1.0.0",
      category: "validation_lesson",
      title: "Repository-standard validation is mandatory",
      summary: "Scoped engineering changes require focused tests, full tests, typecheck, lint, i18n, build, diff validation, and secret review.",
      repositoryEvidence: [".github/workflows/launch-validation.yml", "src/lib/harmony/code/mason-engineering/constitution.ts"],
      relatedFiles: [".github/workflows/launch-validation.yml"],
      relatedSubsystems: ["mason"],
      relatedTests: ["tests/unit/mason-engineering-foundation.test.ts"],
      relatedPrs: [454, 455],
      relatedIssues: [],
      origin: "validation",
      verificationStatus: "verified",
      confidence: 1,
      owner: "Mason",
      createdAt: "2026-07-23T00:00:00.000Z",
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      status: "active",
    },
    {
      id: "memory.append-only-execution-evidence",
      version: "1.0.0",
      category: "security_lesson",
      title: "Execution evidence is append-only and tenant-scoped",
      summary: "Mason execution history is protected by append-only semantics and RLS-backed ownership.",
      repositoryEvidence: ["supabase/migrations/20260717000000_mason_execution_ledger.sql", "src/lib/harmony/code/mason-ledger.ts"],
      relatedFiles: ["src/lib/harmony/code/mason-ledger.ts"],
      relatedSubsystems: ["execution-ledger", "mason"],
      relatedTests: ["tests/unit/mason-ledger.test.ts"],
      relatedPrs: [],
      relatedIssues: [],
      origin: "repository",
      verificationStatus: "verified",
      confidence: 0.95,
      owner: "Ledger",
      createdAt: "2026-07-17T00:00:00.000Z",
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      status: "active",
    },
    {
      id: "memory.forward-only-migrations",
      version: "1.0.0",
      category: "migration_lesson",
      title: "Persistent schema reconciliation is forward-only",
      summary: "Shipped migration history is preserved and schema conflicts are reconciled through forward migrations with clean-chain certification.",
      repositoryEvidence: ["supabase/migrations/20260723000000_reconcile_integration_connections.sql", ".github/workflows/full-migration-chain-certification.yml"],
      relatedFiles: ["supabase/migrations/20260723000000_reconcile_integration_connections.sql"],
      relatedSubsystems: ["supabase", "connector-runtime"],
      relatedTests: ["tests/unit/integration-connections-migration.test.ts"],
      relatedPrs: [450, 451],
      relatedIssues: [],
      origin: "pull_request",
      verificationStatus: "verified",
      confidence: 0.95,
      owner: "AIOS Platform",
      createdAt: "2026-07-23T00:00:00.000Z",
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      status: "active",
    },
  ]),
  patterns: Object.freeze([
    {
      id: "pattern.approval-boundary",
      name: "Approval Pattern",
      version: "1.0.0",
      purpose: "Require an exact Founder decision before governed execution resumes.",
      evidence: ["src/lib/harmony/os/approval-actions.ts", "src/lib/harmony/autonomy/execution-resumption.ts"],
      files: ["src/lib/harmony/os/approval-actions.ts", "src/lib/harmony/autonomy/execution-resumption.ts"],
      usedBy: ["approval-engine", "mason", "connector-runtime"],
      confidence: 0.95,
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      knownLimitations: ["Live authorization remains environment-specific."],
      verificationStatus: "verified",
    },
    {
      id: "pattern.event-mesh-adapter",
      name: "Event Mesh Pattern",
      version: "1.0.0",
      purpose: "Route typed event envelopes through bounded runtime adapters.",
      evidence: ["src/lib/event-mesh/index.ts", "src/lib/event-mesh/envelope.ts"],
      files: ["src/lib/event-mesh/index.ts", "src/lib/event-mesh/envelope.ts"],
      usedBy: ["event-mesh", "ai-workforce"],
      confidence: 0.9,
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      knownLimitations: ["Worker deployment availability is environment-specific."],
      verificationStatus: "verified",
    },
    {
      id: "pattern.supabase-rls",
      name: "Supabase Pattern",
      version: "1.0.0",
      purpose: "Use authenticated server clients with RLS-backed tenant boundaries.",
      evidence: ["src/lib/supabase/server.ts", "supabase/migrations/20260601000000_profiles_and_roles.sql"],
      files: ["src/lib/supabase/server.ts"],
      usedBy: ["authentication", "julius", "approval-engine", "marketplace"],
      confidence: 0.95,
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      knownLimitations: ["Service-role access is not proof of user-scoped behavior."],
      verificationStatus: "verified",
    },
    {
      id: "pattern.connector-policy",
      name: "Connector Pattern",
      version: "1.0.0",
      purpose: "Resolve provider capabilities through a registry and policy-gated runtime.",
      evidence: ["src/lib/integrations/connectors.ts", "src/lib/harmony/autonomy/connector-policy.ts"],
      files: ["src/lib/integrations/connectors.ts", "src/lib/harmony/autonomy/connector-policy.ts"],
      usedBy: ["connector-runtime", "mason", "catalyst"],
      confidence: 0.9,
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      knownLimitations: ["Provider health requires live evidence."],
      verificationStatus: "verified",
    },
    {
      id: "pattern.launch-validation",
      name: "Validation Pattern",
      version: "1.0.0",
      purpose: "Run the repository-standard checks before merge readiness.",
      evidence: [".github/workflows/launch-validation.yml"],
      files: [".github/workflows/launch-validation.yml"],
      usedBy: ["mason"],
      confidence: 1,
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
      knownLimitations: ["CI success does not replace live runtime certification."],
      verificationStatus: "verified",
    },
  ]),
  adrs: Object.freeze([
    {
      id: "adr.founder-governed-merge",
      version: "1.0.0",
      decision: "Mason cannot merge or edit production without explicit Founder authorization.",
      problem: "Engineering automation must not bypass AIOS governance.",
      alternativesConsidered: ["Autonomous merge", "Direct production editing"],
      chosenSolution: "Branch, PR, preview, validation, and Founder approval remain mandatory.",
      tradeoffs: ["Delivery requires an explicit governance checkpoint."],
      evidence: ["src/lib/harmony/code/mason.ts", "src/lib/harmony/autonomy/mason-policy.ts"],
      validation: ["tests/unit/mason-policy.test.ts", "tests/unit/mason.test.ts"],
      affectedSubsystems: ["mason", "approval-engine"],
      owner: "Founder",
      status: "accepted",
      timestamp: "2026-07-23T00:00:00.000Z",
    },
    {
      id: "adr.bounded-repository-intelligence",
      version: "1.0.0",
      decision: "Repository and architecture intelligence use bounded, source-backed runtime manifests.",
      problem: "Unrestricted crawling would expand attack surface and permit unsupported repository claims.",
      alternativesConsidered: ["Unbounded filesystem crawling", "Prompt-directed repository reads"],
      chosenSolution: "Use validated evidence paths, hard limits, and explicit UNKNOWN classifications.",
      tradeoffs: ["Architecture drift requires an explicit catalog update."],
      evidence: ["src/lib/harmony/code/mason-engineering/repository-intelligence.ts", "src/lib/harmony/code/mason-engineering/architectural-intelligence.ts"],
      validation: ["tests/unit/mason-engineering-foundation.test.ts", "tests/unit/mason-architectural-intelligence.test.ts"],
      affectedSubsystems: ["mason"],
      owner: "Mason",
      status: "accepted",
      timestamp: "2026-07-23T00:00:00.000Z",
    },
  ]),
  standards: Object.freeze([
    {
      id: "standard.truth-before-speed",
      version: "1.0.0",
      title: "Truth Before Speed",
      rule: "Verified, inferred, unknown, and blocked claims remain explicitly distinguished.",
      evidence: ["src/lib/harmony/code/mason-engineering/constitution.ts"],
      owner: "Founder",
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
    },
    {
      id: "standard.no-autonomy-from-planning",
      version: "1.0.0",
      title: "Planning Does Not Grant Execution Authority",
      rule: "Engineering context and plans cannot expand mutation, merge, deployment, or approval authority.",
      evidence: ["src/lib/harmony/code/mason.ts", "src/lib/harmony/autonomy/mason-policy.ts"],
      owner: "Founder",
      lastVerifiedAt: "2026-07-23T00:00:00.000Z",
    },
  ]),
}) as EngineeringKnowledgeCatalog;

export function getDefaultEngineeringKnowledgeCatalog(
  repository: string | null | undefined,
): EngineeringKnowledgeCatalog {
  if (repository?.trim().toLowerCase() === AIOS_PLATFORM_REPOSITORY.toLowerCase()) return AIOS_ENGINEERING_KNOWLEDGE;
  return {
    catalogId: "mason.engineering-knowledge",
    version: "0.0.0",
    asOf: "1970-01-01T00:00:00.000Z",
    memories: [],
    patterns: [],
    adrs: [],
    standards: [],
  };
}
