import type { CompanyTemplate } from "./types";

/**
 * The launch set of Company Templates. Each provisions a complete autonomous
 * company — Harmony (chief of staff) always coordinates; specialists, objectives,
 * connectors (config-only), branding, and knowledge seeds are tuned per vertical.
 * Connector slugs are hints; those not yet on the runtime install as config and
 * activate when their provider client + Layer-1 credentials land.
 */
export const COMPANY_TEMPLATES: readonly CompanyTemplate[] = [
  {
    id: "tpl_saas_startup",
    slug: "saas-startup",
    name: "SaaS Startup",
    industry: "Software / SaaS",
    summary: "A product-led SaaS company built to reach product-market fit and scale ARR.",
    version: "1.0.0",
    departments: ["Product & Engineering", "Growth & Marketing", "Sales", "Customer Success", "Finance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "catalyst", role: "Growth Lead" },
      { key: "atlas", role: "Operations" },
      { key: "ambassador", role: "Customer Success" },
      { key: "ledger", role: "Finance / CFO" },
    ],
    objectives: ["Reach product-market fit", "Grow to $1M ARR", "Keep monthly churn under 5%"],
    connectors: ["github", "slack", "hubspot", "notion", "stripe"],
    brandingTone: "Modern, confident, product-forward",
    knowledgeSeeds: [
      "SaaS north-star metrics: ARR, NRR, churn, CAC:LTV, activation.",
      "Product-led growth playbook: free trial → activation → expansion.",
    ],
    tags: ["saas", "startup", "b2b", "plg"],
  },
  {
    id: "tpl_aviation_claims",
    slug: "aviation-claims",
    name: "Aviation Claims Company",
    industry: "Aviation / Insurance Claims",
    summary: "A regulated flight-delay/cancellation claims operation optimized for cycle time and compliance.",
    version: "1.0.0",
    departments: ["Claims Operations", "Regulatory Compliance", "Customer Care", "Legal", "Finance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "aegis", role: "Compliance & Risk" },
      { key: "auditor", role: "Quality Auditor" },
      { key: "ambassador", role: "Claimant Care" },
      { key: "ledger", role: "Finance / Payouts" },
    ],
    objectives: ["Cut average claim cycle time by 40%", "Maintain full regulatory compliance", "Raise claimant CSAT above 90%"],
    connectors: ["gmail", "google-drive", "jira", "hubspot"],
    brandingTone: "Trustworthy, precise, reassuring",
    knowledgeSeeds: [
      "EU261 / passenger-rights claim eligibility and evidence requirements.",
      "Claim intake → validation → carrier negotiation → payout workflow.",
    ],
    tags: ["aviation", "claims", "insurance", "regulated"],
  },
  {
    id: "tpl_law_firm",
    slug: "law-firm",
    name: "Law Firm",
    industry: "Legal Services",
    summary: "A modern practice run for matter throughput, utilization, and airtight compliance.",
    version: "1.0.0",
    departments: ["Practice Operations", "Client Intake", "Compliance", "Knowledge Management", "Finance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "aegis", role: "Compliance & Conflicts" },
      { key: "auditor", role: "Matter Auditor" },
      { key: "atlas", role: "Practice Operations" },
      { key: "ledger", role: "Billing / Finance" },
    ],
    objectives: ["Increase matter throughput", "Improve billable utilization", "Pass every compliance review"],
    connectors: ["google-drive", "gmail", "google-calendar", "notion"],
    brandingTone: "Authoritative, classic, discreet",
    knowledgeSeeds: [
      "Matter lifecycle: intake → conflict check → engagement → billing.",
      "Conflict-of-interest and client-confidentiality checklists.",
    ],
    tags: ["legal", "law", "professional-services"],
  },
  {
    id: "tpl_accounting_firm",
    slug: "accounting-firm",
    name: "Accounting Firm",
    industry: "Accounting / Advisory",
    summary: "A bookkeeping, tax, and advisory practice tuned for accuracy and deadline discipline.",
    version: "1.0.0",
    departments: ["Bookkeeping", "Tax", "Advisory", "Client Operations", "Compliance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "ledger", role: "Lead Accountant" },
      { key: "auditor", role: "Reconciliation Auditor" },
      { key: "ambassador", role: "Client Operations" },
      { key: "aegis", role: "Regulatory Compliance" },
    ],
    objectives: ["Achieve 100% on-time filings", "Reduce close cycle to 5 days", "Grow advisory revenue"],
    connectors: ["google-sheets", "gmail", "quickbooks", "hubspot"],
    brandingTone: "Precise, reliable, understated",
    knowledgeSeeds: [
      "Month-end close checklist and reconciliation controls.",
      "GAAP fundamentals and filing-deadline calendar.",
    ],
    tags: ["accounting", "tax", "finance", "professional-services"],
  },
  {
    id: "tpl_real_estate",
    slug: "real-estate-company",
    name: "Real Estate Company",
    industry: "Real Estate",
    summary: "A brokerage run for listing velocity, lead conversion, and smooth transactions.",
    version: "1.0.0",
    departments: ["Listings & Marketing", "Transactions", "Client Relations", "Operations", "Finance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "catalyst", role: "Marketing & Listings" },
      { key: "ambassador", role: "Client Relations" },
      { key: "atlas", role: "Transaction Coordinator" },
      { key: "ledger", role: "Finance / Commissions" },
    ],
    objectives: ["Increase listing velocity", "Lift lead-to-close conversion", "Shorten transaction cycle time"],
    connectors: ["hubspot", "gmail", "google-calendar", "google-drive"],
    brandingTone: "Aspirational, warm, polished",
    knowledgeSeeds: [
      "Transaction pipeline: lead → showing → offer → escrow → close.",
      "Disclosure and contingency checklists.",
    ],
    tags: ["real-estate", "brokerage", "sales"],
  },
  {
    id: "tpl_healthcare_practice",
    slug: "healthcare-practice",
    name: "Healthcare Practice",
    industry: "Healthcare",
    summary: "A patient-centered practice tuned for throughput, HIPAA compliance, and collections.",
    version: "1.0.0",
    departments: ["Patient Operations", "Scheduling", "Billing", "Compliance", "Care Coordination"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "aegis", role: "HIPAA Compliance" },
      { key: "ambassador", role: "Patient Experience" },
      { key: "ledger", role: "Billing / Collections" },
      { key: "auditor", role: "Records Auditor" },
    ],
    objectives: ["Improve patient throughput", "Maintain HIPAA compliance", "Raise clean-claim collection rate"],
    connectors: ["google-calendar", "gmail", "google-drive"],
    brandingTone: "Caring, trustworthy, calm",
    knowledgeSeeds: [
      "HIPAA privacy and security fundamentals.",
      "Patient intake → visit → coding → claim workflow.",
    ],
    tags: ["healthcare", "practice", "regulated"],
  },
  {
    id: "tpl_manufacturing",
    slug: "manufacturing-company",
    name: "Manufacturing Company",
    industry: "Manufacturing",
    summary: "A plant run for equipment effectiveness, on-time delivery, and quality.",
    version: "1.0.0",
    departments: ["Production Operations", "Supply Chain", "Quality", "Sales", "Finance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "atlas", role: "Production Operations" },
      { key: "aegis", role: "Quality & Safety" },
      { key: "catalyst", role: "Sales & Demand" },
      { key: "ledger", role: "Finance / Costing" },
    ],
    objectives: ["Raise OEE", "Hit 98% on-time delivery", "Cut defect rate"],
    connectors: ["jira", "google-sheets", "slack"],
    brandingTone: "Industrial, solid, dependable",
    knowledgeSeeds: [
      "Lean/OEE fundamentals and takt-time planning.",
      "Supplier management and inventory control basics.",
    ],
    tags: ["manufacturing", "operations", "supply-chain"],
  },
  {
    id: "tpl_restaurant_group",
    slug: "restaurant-group",
    name: "Restaurant Group",
    industry: "Food & Hospitality",
    summary: "A multi-location group run for food cost, covers growth, and labor efficiency.",
    version: "1.0.0",
    departments: ["Operations", "Marketing", "Supply & Inventory", "People", "Finance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "atlas", role: "Multi-unit Operations" },
      { key: "catalyst", role: "Marketing & Loyalty" },
      { key: "ambassador", role: "Guest Experience" },
      { key: "ledger", role: "Finance / Food Cost" },
    ],
    objectives: ["Hold food cost under 30%", "Grow covers per location", "Improve labor efficiency"],
    connectors: ["slack", "google-sheets", "hubspot"],
    brandingTone: "Vibrant, hospitable, appetizing",
    knowledgeSeeds: [
      "Food-cost and menu-engineering fundamentals.",
      "Labor scheduling and inventory par levels.",
    ],
    tags: ["restaurant", "hospitality", "multi-unit"],
  },
  {
    id: "tpl_ecommerce",
    slug: "ecommerce-business",
    name: "E-commerce Business",
    industry: "E-commerce / Retail",
    summary: "A DTC store run for order value, healthy unit economics, and fulfillment SLAs.",
    version: "1.0.0",
    departments: ["Merchandising", "Growth & Marketing", "Fulfillment & Operations", "Customer Care", "Finance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "catalyst", role: "Growth & Performance" },
      { key: "atlas", role: "Fulfillment & Ops" },
      { key: "ambassador", role: "Customer Care" },
      { key: "ledger", role: "Finance / Unit Economics" },
    ],
    objectives: ["Raise average order value", "Improve CAC:LTV to 1:3+", "Meet a 2-day fulfillment SLA"],
    connectors: ["shopify", "hubspot", "gmail", "google-sheets"],
    brandingTone: "Energetic, conversion-focused, on-brand",
    knowledgeSeeds: [
      "E-commerce unit economics: AOV, contribution margin, CAC:LTV.",
      "Retention and lifecycle-marketing fundamentals.",
    ],
    tags: ["ecommerce", "dtc", "retail"],
  },
  {
    id: "tpl_startup_accelerator",
    slug: "startup-accelerator",
    name: "Startup Accelerator",
    industry: "Venture / Programs",
    summary: "An accelerator run for cohort throughput, portfolio milestones, and follow-on rate.",
    version: "1.0.0",
    departments: ["Program Operations", "Sourcing & Deal Flow", "Mentorship", "Portfolio Success", "Finance"],
    workforce: [
      { key: "harmony", role: "Chief of Staff" },
      { key: "horizon", role: "Strategy & Portfolio" },
      { key: "catalyst", role: "Sourcing & Deal Flow" },
      { key: "ambassador", role: "Founder Success" },
      { key: "ledger", role: "Finance / Fund Ops" },
    ],
    objectives: ["Run cohorts on schedule", "Hit portfolio milestone targets", "Increase follow-on funding rate"],
    connectors: ["notion", "slack", "gmail", "hubspot"],
    brandingTone: "Visionary, energetic, founder-first",
    knowledgeSeeds: [
      "Cohort program playbook: sourcing → selection → curriculum → demo day.",
      "Portfolio KPI tracking and follow-on readiness.",
    ],
    tags: ["accelerator", "venture", "programs"],
  },
] as const;

/** Look up a template by slug. */
export function templateBySlug(slug: string): CompanyTemplate | undefined {
  return COMPANY_TEMPLATES.find((t) => t.slug === slug);
}

/** Look up a template by id. */
export function templateById(id: string): CompanyTemplate | undefined {
  return COMPANY_TEMPLATES.find((t) => t.id === id);
}
